#!/bin/bash

if [ $(whoami) != 'root' ]; then
	echo "You need to be ROOT to execute this command";
else	
	if [[ $(lsb_release -a | grep Manjaro) == '' ]]; then
		echo "Working on archlinux mirrorlist..."
		if [[ -f /etc/pacman.d/mirrorlist.pacnew ]] && [[ ! $(cat /etc/pacman.d/mirrorlist.pacnew) == ' ' ]]; then
			mv /etc/pacman.d/mirrorlist.pacnew /etc/pacman.d/mirrorlist.backup && sync;
		fi
		if [[ ! -f /etc/pacman.d/mirrorlist.backup ]] || [[ $(cat /etc/pacman.d/mirrorlist.backup) == ' ' ]]; then
			cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup && sync;
		fi		
		if [[ -f /etc/pacman.d/mirrorlist.backup ]] && [[ ! $(cat /etc/pacman.d/mirrorlist.backup) == ' ' ]]; then
			sed -i 's/^#Server/Server/' /etc/pacman.d/mirrorlist.backup && sync;
			rankmirrors --verbose -n 10 /etc/pacman.d/mirrorlist.backup | grep -v '#' > /etc/pacman.d/mirrorlist && sync;
			chmod +r /etc/pacman.d/mirrorlist;
		fi
	else
		echo "Working on manjaro mirrorlist..."
		rankmirrors -g;
	fi
	
	if [[ -f /etc/pacman.d/antergos-mirrorlist ]]; then
		echo "Working on antergos mirrorlist..."
		if [[ -f /etc/pacman.d/antergos-mirrorlist.pacnew ]] && [[ ! $(cat /etc/pacman.d/antergos-mirrorlist.pacnew) == ' ' ]]; then
			mv /etc/pacman.d/antergos-mirrorlist.pacnew /etc/pacman.d/antergos-mirrorlist.backup && sync;
		fi
		if [[ ! -f /etc/pacman.d/antergos-mirrorlist.backup ]] || [[ $(cat /etc/pacman.d/antergos-mirrorlist.backup) == ' ' ]]; then
			cp /etc/pacman.d/antergos-mirrorlist /etc/pacman.d/antergos-mirrorlist.backup && sync;
		fi			
		if [[ -f /etc/pacman.d/antergos-mirrorlist.backup ]] && [[ ! $(cat /etc/pacman.d/antergos-mirrorlist.backup) == ' ' ]]; then
			sed -i 's/^#Server/Server/' /etc/pacman.d/antergos-mirrorlist.backup && sync;
			rankmirrors --verbose -n 10 /etc/pacman.d/antergos-mirrorlist.backup | grep -v '#' > /etc/pacman.d/antergos-mirrorlist && sync;
			chmod +r /etc/pacman.d/antergos-mirrorlist;
		fi
	fi
	
	pacman-optimize && sync
fi
