#!/bin/bash

if [ $(whoami) != 'root' ]; then
	echo "You need to be ROOT to execute this command";
else
	echo "Working on pacman mirrorlist..."	
	if [[ -f /etc/pacman.d/mirrorlist.pacnew ]] && [[ ! $(cat /etc/pacman.d/mirrorlist.pacnew) == ' ' ]]; then
		mv /etc/pacman.d/mirrorlist.pacnew /etc/pacman.d/mirrorlist.backup;
	fi
	if [[ ! -f /etc/pacman.d/mirrorlist.backup ]] || [[ $(cat /etc/pacman.d/mirrorlist.backup) == ' ' ]]; then
		cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup;
	fi
	if [[ "$(cat /etc/pacman.d/mirrorlist.backup)" != " " ]]; then
		sed -i 's/^#Server = https/Server = https/' /etc/pacman.d/mirrorlist.backup;
		rankmirrors -n 10 /etc/pacman.d/mirrorlist.backup | grep -v '#' > /etc/pacman.d/mirrorlist;
		chmod +r /etc/pacman.d/mirrorlist;
	fi
	
	echo "Working on antergos mirrorlist..."
	if [[ -f /etc/pacman.d/antergos-mirrorlist.pacnew ]] && [[ ! $(cat /etc/pacman.d/antergos-mirrorlist.pacnew) == ' ' ]]; then
		mv /etc/pacman.d/antergos-mirrorlist.pacnew /etc/pacman.d/antergos-mirrorlist.backup;
	fi
	if [[ ! -f /etc/pacman.d/antergos-mirrorlist.backup ]] || [[ $(cat /etc/pacman.d/antergos-mirrorlist.backup) == ' ' ]]; then
		cp /etc/pacman.d/antergos-mirrorlist /etc/pacman.d/antergos-mirrorlist.backup;
	fi
	if [[ "$(cat /etc/pacman.d/antergos-mirrorlist.backup)" != " " ]]; then
		sed -i 's/^#Server/Server/' /etc/pacman.d/antergos-mirrorlist.backup;
		rankmirrors -n 10 /etc/pacman.d/antergos-mirrorlist.backup | grep -v '#' > /etc/pacman.d/antergos-mirrorlist;
		chmod +r /etc/pacman.d/antergos-mirrorlist;
	fi
	
	pacman-optimize
fi
